### ISSUE TITLE
The latest v0.12.12 has been yanked from PyPI

### ISSUE THREAD

**Issue by maresb** [conda-forge/cachecontrol-feedstock#15]
### Comment:

Please see https://github.com/ionrock/cachecontrol/issues/286. In brief, an important extra-dependency has been changed from `lockfile` to `filelock` in a patch release, and this is causing unexpected breakage. The plan was to yank v0.12.12 and release it as v0.13. It's been yanked, but awkwardly not rereleased.

For consistency with PyPI, should we mark v0.12.12 as broken?

**Comment by ocefpaf** [comment]
> For consistency with PyPI, should we mark v0.12.12 as broken?

Yep. Do you want to send a PR to mark them?

**Comment by maresb** [comment]
Closed by #529
